### ISSUE TITLE
Publishing M-ArkDow_ahk2 as an ahkpm package?

### ISSUE THREAD

**Issue by joshuacc** [TheArkive/M-ArkDown_ahk2#1]
Hi @TheArkive. I'm wondering if you'd be interested in publishing M-ArkDow_ahk2 as an ahkpm package?

ahkpm is a package manager built specifically for AutoHotkey libraries.

- Repo: https://github.com/joshuacc/ahkpm
- Docs: https://ahkpm.dev/

I've written a [guide on how to publish ahkpm packages](https://ahkpm.dev/docs/guides/publishing/) and it likely wouldn't take much time at all.

The main thing I noticed that you might need to change is to start tagging new versions with the appropriate semantic version number. e.g. `git tag 1.3.18`. 

I'd be happy to open up a PR adding the `ahkpm.json` file if you're interested.

**Comment by TheArkive** [comment]
That sounds interesting.  Just a few questions:

* Is this AHK repo a standalone package manager or is it meant to be used with something like VSCode or Sublime?
* How many people curate the list currently?
* Will you need to release a new version of ahkpm for every package added?  Or is there an internal list that can be edited without disrupting the package manager itself?

I've thought about how a package management system would work with AHK for a while.  Glad to see someone finally try something 👍 

I like the idea of contributing, but I might prefer to make separate repos for the packages (at least at first).

**Comment by joshuacc** [comment]
> Is this AHK repo a standalone package manager or is it meant to be used with something like VSCode or Sublime?

It is a standalone package manager written in Go. It would, however, be relatively easy to build editor extensions wrapping it's functionality.

> How many people curate the list currently?

If by "list" you mean the list of packages on https://ahkpm.dev/packages, technically it isn't curated at all. It is derived from searching the GitHub API for repositories with the topic `ahkpm-package`. The page is regenerated every 24 hours.

> Will you need to release a new version of ahkpm for every package added? Or is there an internal list that can be edited without disrupting the package manager itself?

ahkpm doesn't need to be updated for new packages, because it doesn't use a list for anything but package discovery. ahkpm can be used to install any GitHub repository as a package, even if it doesn't have an `ahkpm.json` file or the `ahkpm-package` topic. The topic usage is merely for discovery, and the `ahkpm.json` file provides additional benefits (like specifying the main file to include, as well as any dependencies that the package itself might have).

"Publishing" a package in the sense that I used it above basically means just adding the `ahkpm.json` file and `ahkpm-package` topic to an existing GitHub repo in order to provide a better experience for ahkpm users who are installing your package, and easier discovery via the packages page above and `ahkpm search`.

I hope that clarifies things, but if not, just let me know what other questions you have!

**Comment by TheArkive** [comment]
Ok that sounds pretty straight forward.  Go ahead and make the PR if you don't mind.  Then I'll add the topic.

**Comment by TheArkive** [comment]
Did you make a pull request and I missed it somehow?

**Comment by joshuacc** [comment]
@TheArkive Apologies for the delay. Things got a bit hectic in my life recently, but I have opened up PR #2 adding the ahkpm.json file.

**Comment by TheArkive** [comment]
Understood.  I didn't mean to rush anything.  I wasn't in any hurry. Hope you are doing better soon.

I merged the commit.

**Comment by joshuacc** [comment]
Thanks @TheArkive. Now that the PR has been merged, do you mind adding the `ahkpm-package` topic to this repo so it will show up on the [ahkpm packages page](https://ahkpm.dev/packages)? I think once that's done, this issue can be closed. :)

**Comment by TheArkive** [comment]
Ok done.  I'll wait for ya to do a test and verify that it's working before I close the issue.

**Comment by joshuacc** [comment]
Success!

https://ahkpm.dev/packages

![image](https://user-images.githubusercontent.com/171086/211081282-b119c6f8-b42d-4715-b11b-eac367b4c2ef.png)
